[package]
name = "traintables_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
reqwest = { version = "0.12.26", default-features = false, features = ["rustls-tls", "json"] }
zip = { version = "7.0.0", default-features = false, features = ["deflate"] }
csv = "1.4.0"
