[package]
name = "gtfs"
version = "0.1.0"
edition = "2024"

[dependencies]
traintables_core = { path = "../core" }
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
csv = "1.4.0"
